# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
puts "Ladies and Gentlemen, your elected officials"
Politician.create [
{
	name: "Barbara Boxer",
	image: "",
	position1: "United States Senator",
	position2: "Senate Committee on Rules and Administration",
	state_id: 1,
	district: nil,
	party: "D",
	sworn_in: 1993,
	person_defeated: "",
	votes_w_party: 0.97,
	votes_vs_party: 0,
	abstains: "",
},
{
	name: "Dianne Feinstein",
	image: "",
	position1: "United States Senator",
	position2: "",
	state_id: 1,
	district: nil,
	party: "D",
	sworn_in: 1992,
	person_defeated: "",
	votes_w_party: 0.97,
	votes_vs_party: nil,
	abstains: "",
},
{
	name: "Karen Bass",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "37",
	party: "D",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: nil,
},
{
	name: "Xavier Becerra",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "34",
	party: "D",
	sworn_in: 1993,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.04,
},
{
	name: "Ami Bera",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "7",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.89,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Julia Brownley",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "26",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.92,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Ken Calvert",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "42",
	party: "R",
	sworn_in: 1993,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "John Campbell",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "45",
	party: "R",
	sworn_in: 2005,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.42,
},
{
	name: "Lois Capps",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "24",
	party: "D",
	sworn_in: 1998,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Tony Cardenas",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "29",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.06,
},
{
	name: "Judy Chu",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "27",
	party: "D",
	sworn_in: 2009,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.04,
},
{
	name: "Paul Cook",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "8",
	party: "R",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Jim Costa",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "16",
	party: "D",
	sworn_in: 2005,
	person_defeated: "",
	votes_w_party: 0.76,
	votes_vs_party: nil,
	abstains: 0.05,
},
{
	name: "Susan Davis",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "53",
	party: "D",
	sworn_in: 2001,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Jeff Denham",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "10",
	party: "R",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.92,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Anna Eshoo",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "18",
	party: "D",
	sworn_in: 1993,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Sam Farr",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "20",
	party: "R",
	sworn_in: 1993,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.04,
},
{
	name: "John Garamendi",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "3",
	party: "D",
	sworn_in: 2009,
	person_defeated: "",
	votes_w_party: 0.92,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Janice Hahn",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "44",
	party: "D",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Michael Honda",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "17",
	party: "D",
	sworn_in: 2001,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.06,
},
{
	name: "Jared Huffman",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "2",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Duncan Hunter",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "50",
	party: "R",
	sworn_in: 2009,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.07,
},
{
	name: "Darrell Issa",
	image: "",
	position1: "United States Representative",
	position2: "Chair, House Committee on Oversight and Government Reform",
	state_id: 1,
	district: "49",
	party: "R",
	sworn_in: 2001,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Doug LaMalfa",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "1",
	party: "R",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.97,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Barbara Lee",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "13",
	party: "D",
	sworn_in: 1998,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.04,
},
{
	name: "Zoe Lofgren",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "19",
	party: "D",
	sworn_in: 1995,
	person_defeated: "",
	votes_w_party: 0.92,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Alan Lowenthal",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "47",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Doris Matsui",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "6",
	party: "D",
	sworn_in: 2005,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Kevin McArthy",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "23",
	party: "R",
	sworn_in: 2007,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Tom McClintock",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "4",
	party: "R",
	sworn_in: 2009,
	person_defeated: "",
	votes_w_party: 0.91,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Howard McKeon",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "25",
	party: "R",
	sworn_in: 1993,
	person_defeated: "",
	votes_w_party: 0.92,
	votes_vs_party: nil,
	abstains: 0.03
},
{
	name: "Jerry McNerney",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "9",
	party: "D",
	sworn_in: 2007,
	person_defeated: "",
	votes_w_party: 0.92,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Gary Miller",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "31",
	party: "R",
	sworn_in: 1999,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.31,
},
{
	name: "George Miller",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "11",
	party: "D",
	sworn_in: 1975,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.10,
},
{
	name: "Grace Napolitano",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "32",
	party: "D",
	sworn_in: 1999,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.04,
},
{
	name: "Gloria Negrete McLeod",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "35",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.13,
},
{
	name: "Devin Nunes",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "22",
	party: "R",
	sworn_in: 2003,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.03,
},
{
	name: "Nancy Pelosi",
	image: "",
	position1: "United States Representative",
	position2: "House Minority Leader",
	state_id: 1,
	district: "12",
	party: "D",
	sworn_in: 1987,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.09,
},
{
	name: "Scott Peters",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "52",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.85,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Dana Rohrabacher",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "48",
	party: "R",
	sworn_in: 1989,
	person_defeated: "",
	votes_w_party: 0.88,
	votes_vs_party: nil,
	abstains: 0.07,
},
{
	name: "Lucille Roybal-Allard",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "40",
	party: "D",
	sworn_in: 1993,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Edward Royce",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "39",
	party: "R",
	sworn_in: 1993,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Paul Ruiz",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "36",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.85,
	votes_vs_party: nil,
	abstains: 0.03,
},
{
	name: "Loretta Sanchez",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "46",
	party: "D",
	sworn_in: 1997,
	person_defeated: "",
	votes_w_party: 0.93,
	votes_vs_party: nil,
	abstains: 0.06,
},
{
	name: "Linda Sanchez",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "38",
	party: "D",
	sworn_in: 2003,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Adam Schiff",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "28",
	party: "D",
	sworn_in: 2001,
	person_defeated: "",
	votes_w_party: 0.97,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Brad Sherman",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "30",
	party: "D",
	sworn_in: 1997,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Jackie Speier",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "14",
	party: "D",
	sworn_in: 2008,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.07,
},
{
	name: "Eric Swalwell",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "15",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.93,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Mark Takano",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "41",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Mike Thompson",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "5",
	party: "D",
	sworn_in: 1999,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "David Valadao",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "21",
	party: "R",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.92,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Juan Vargas",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "51",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.93,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Maxine Waters",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "43",
	party: "D",
	sworn_in: 1991,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.07,
},
{
	name: "Henry Waxman",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 1,
	district: "33",
	party: "D",
	sworn_in: 1975,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.07,
},
{
	name: "Kirsten Gillibrand",
	image: "",
	position1: "United States Senator",
	position2: "",
	state_id: 2,
	district: nil,
	party: "D",
	sworn_in: 2009,
	person_defeated: "",
	votes_w_party: 0.98,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Chuck Schumer",
	image: "",
	position1: "United States Senator",
	position2: "",
	state_id: 2,
	district: nil,
	party: "D",
	sworn_in: 1999,
	person_defeated: "",
	votes_w_party: 0.98,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Timothy Bishop",
	image: "",
	position1: "United States Representative", 
	position2: "",
	state_id: 2,
	district: "1",
	party: "D",
	sworn_in: 2003,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Yvette Clarke",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "9",
	party: "D",
	sworn_in: 2007,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.05,
},
{
	name: "Chris Collins",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "27",
	party: "R",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Joseph Crowley",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "14",
	party: "D",
	sworn_in: 1999,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.03,
},
{
	name: "Eliot Engel",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "16",
	party: "D",
	sworn_in: 1989,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.05,
},
{
	name: "Christopher Gibson",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "19",
	party: "R",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.74,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Michael Grimm",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "11",
	party: "R",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.88,
	votes_vs_party: nil,
	abstains: 0.08
},
{
	name: "Richard Hanna",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "22",
	party: "R",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.87,
	votes_vs_party: nil,
	abstains: 0.08,
},
{
	name: "Brian Higgins",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "26",
	party: "D",
	sworn_in: 2005,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.06,
},
{
	name: "Steve Israel",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "3",
	party: "D",
	sworn_in: 2001,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Hakeem Jeffries",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "8",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.97,
	votes_vs_party: nil,
	abstains: 0.03,
},
{
	name: "Peter King",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "2",
	party: "R",
	sworn_in: 1993,
	person_defeated: "",
	votes_w_party: 0.88,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Nita Lowey",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "17",
	party: "D",
	sworn_in: 1989,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Daniel Maffei",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "24",
	party: "D",
	sworn_in: 2009,
	person_defeated: "",
	votes_w_party: 0.81,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Carolyn Maloney",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "12",
	party: "D",
	sworn_in: 1993,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.04,
},
{
	name: "Sean Maloney",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "18",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.85,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Carolyn McCarthy",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "4",
	party: "D",
	sworn_in: 1997,
	person_defeated: "",
	votes_w_party: 0.93,
	votes_vs_party: nil,
	abstains: 0.65,
},
{
	name: "Gregory Meeks",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "5",
	party: "D",
	sworn_in: 1997,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.08,
},
{
	name: "Grace Meng",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "8",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.06,
},
{
	name: "Jerrold Nadler",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "10",
	party: "D",
	sworn_in: 1992,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "William Owens",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "21",
	party: "D",
	sworn_in: 2009,
	person_defeated: "",
	votes_w_party: 0.76,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Charles Rangel",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "13",
	party: "D",
	sworn_in: 1971,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.19,
},
{
	name: "Tom Reed",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "23",
	party: "R",
	sworn_in: 2010,
	person_defeated: "",
	votes_w_party: 0.91,
	votes_vs_party: nil,
	abstains: 0.05,
},
{
	name: "Jose Serrano",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "15",
	party: "D",
	sworn_in: 1989,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Louise Slaughter",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "25",
	party: "D",
	sworn_in: 1987,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.09,
},
{
	name: "Paul Tonko",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "20",
	party: "D",
	sworn_in: 2009,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Nydia Valazquez",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 2,
	district: "7",
	party: "D",
	sworn_in: 1993,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.05,
},
{
	name: "Richard Durbin",
	image: "",
	position1: "United States Senator",
	position2: "Assistant Majority Leader",
	state_id: 3,
	district: nil,
	party: "D",
	sworn_in: 1997,
	person_defeated: "",
	votes_w_party: 0.98,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Mark Kirk",
	image: "",
	position1: "United States Senator",
	position2: "",
	state_id: 3,
	district: nil,
	party: "R",
	sworn_in: 2010,
	person_defeated: "",
	votes_w_party: 0.75,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Cheri Bustos",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "17",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.87,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Danny Davis",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "7",
	party: "D",
	sworn_in: 1997,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.06,
},
{
	name: "Rodney Davis",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "13",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.92,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Tammy Duckworth",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "8",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.91,
	votes_vs_party: nil,
	abstains: 0.03,
},
{
	name: "William Enyart",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "12",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.89,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Bill Foster",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "11",
	party: "D",
	sworn_in: 2008,
	person_defeated: "",
	votes_w_party: 0.89,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Luis Gutierrez",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "4",
	party: "D",
	sworn_in: 1993,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.18,
},
{
	name: "Randy Hultgren",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "14",
	party: "D",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Robin Kelly",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "2",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.97,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Adam Kinzinger",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "16",
	party: "R",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.93,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Daniel Lipinski",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "3",
	party: "D",
	sworn_in: 2005,
	person_defeated: "",
	votes_w_party: 0.86,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Mike Quigley",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "5",
	party: "D",
	sworn_in: 2009,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.03,
},
{
	name: "Peter Roskam",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "6",
	party: "D",
	sworn_in: 2007,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Bobby Rush",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "1",
	party: "D",
	sworn_in: 1993,
	person_defeated: "",
 	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.42
},
{
	name: "Janice Schakowsky",
	image: "",
	position1: "United States Representative",
	position2: "", 
	state_id: 3,
	district: "9",
	party: "D",
	sworn_in: 1999,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Bradley Schneider",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "10",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.90,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Aaron Schock",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "18",
	party: "R",
	sworn_in: 2009,
	person_defeated: "",
	votes_w_party: 0.93,
	votes_vs_party: nil,
	abstains: 0.05,
},
{
	name: "John Shimkus",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 3,
	district: "15",
	party: "D",
	sworn_in: 1997,
	person_defeated: "",
	votes_w_party: 0.93,
	votes_vs_party: nil,
	abstains: 0.06,
},
{
	name: "Sherrod Brown",
	image: "",
	position1: "United States Senator",
	position2: "",
	state_id: 4,
	district: nil,
	party: "D",
	sworn_in: 2007,
	person_defeated: "",
	votes_w_party: 0.97,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Rob Portman",
	image: "",
	position1: "United States Senator",
	position2: "",
	state_id: 4,
	district: nil,
	party: "R",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.89,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Joyce Beatty",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "3",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "John Boehner",
	image: "",
	position1: "United States Representative",
	position2: "Speaker of the House",
	state_id: 4,
	district: "8",
	party: "D",
	sworn_in: 1991,
	person_defeated: "",
	votes_w_party: 0.91,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Steve Chabot",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "1",
	party: "R",
	sworn_in: 1995,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Marcia Fudge",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "11",
	party: "D",
	sworn_in: 2008,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.06,
},
{
	name: "Bob Gibbs",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "7",
	party: "R",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Bill Johnson",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "6",
	party: "R",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Jim Jordan",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "4",
	party: "R",
	sworn_in: 2007,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "David Joyce",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "14",
	party: "R",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.91,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Marcy Kaptur",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "9",
	party: "D",
	sworn_in: 1983,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.04,
},
{
	name: "Robert Latta",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "5",
	party: "D",
	sworn_in: 2007,
	person_defeated: "",
	votes_w_party: 0.98,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "James Renacci",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "16",
	party: "R",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Tim Ryan",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "13",
	party: "D",
	sworn_in: 2003,
	person_defeated: "",
	votes_w_party: 0.92,
	votes_vs_party: nil,
	abstains: 0.06,
},
{
	name: "Steve Stivers",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "15",
	party: "D",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.93,
	votes_vs_party: nil,
	abstains: 0.02,
},
{
	name: "Patrick Tiberi",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "12",
	party: "R",
	sworn_in: 2001,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.03,
},
{
	name: "Michael Turner",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "10",
	party: "R",
	sworn_in: 2003,
	person_defeated: "",
	votes_w_party: 0.92,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Brad Wenstrup",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 4,
	district: "2",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
 	votes_w_party: 0.96,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Dean Heller",
	image: "",
	position1: "United States Senator",
	position2: "",
	state_id: 5,
	district: nil,
	party: "R",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.77,
	votes_vs_party: nil,
	abstains: 0.03,
},
{
	name: "Harry Reid",
	image: "",
	position1: "United States Senator",
	position2: "Senate Majority Leader",
	state_id: 5,
	district: nil,
	party: "D",
	sworn_in: 1987,
	person_defeated: "",
	votes_w_party: 0.93,
	votes_vs_party: nil,
	abstains: 0,
},
{
	name: "Mark Amodei",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 5,
	district: "2",
	party: "R",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.94,
	votes_vs_party: nil,
	abstains: 0.09,
},
{
	name: "Joseph Heck",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 5,
	district: "3",
	party: "R",
	sworn_in: 2011,
	person_defeated: "",
	votes_w_party: 0.91,
	votes_vs_party: nil,
	abstains: 0.01,
},
{
	name: "Steven Horsford",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 5,
	district: "4",
	party: "D",
	sworn_in: 2013,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0.15,
},
{
	name: "Dina Titus",
	image: "",
	position1: "United States Representative",
	position2: "",
	state_id: 5,
	district: "1",
	party: "D",
	sworn_in: 2009,
	person_defeated: "",
	votes_w_party: 0.95,
	votes_vs_party: nil,
	abstains: 0,
},
]

puts "States"
State.create [
{
	state: "CA",
},
{
	state: "NY",
},
{
	state: "IL",
},
{
	state: "OH",
},
{
	state: "NV",
},
]

puts "Written Statements loaded"
WrittenStatement.create [
{
	statements: "Government Spending",
	body: "Statement on changing the spending culture in Washington",
	path: "http://votesmart.org/public-statement/873651/changing-the-spending-culture-in-washington#.U83nH4BdWQw",
	politician_id: 108,
},
{
	statements: "House votes for 37th time against Obamacare",
	body: "House votes again to repeal or defund Obamacare",
	path: "http://thehill.com/blogs/floor-action/house/300315-house-votes-to-repeal-obamacare",
	politician_id: 108,
},
{
	statements: "Boehner Demands Delay of Individual Mandate",
	body: "House Republican leadership demands delay of Obamacare individual mandate",
	path: "http://talkingpointsmemo.com/livewire/boehner-obamacare-individual-mandate-delay",
	politician_id: 108,
},
{
	statements: "Obamacare Enrollment",
	body: "Statement on Ohio Enrollment Numbers",
	path: "http://votesmart.org/public-statement/868077/boehner-statement-on-ohios-obamacare-enrollment-numbers#.U87FboBdWQw",
	politician_id: 108,
},
{
	statements: "House votes for 54th time against Obamacare",
	body: "House votes again to repeal or defund Obamacare",
	path: "http://www.washingtonpost.com/blogs/the-fix/wp/2014/03/21/the-house-has-voted-54-times-in-four-years-on-obamacare-heres-the-full-list/",
	politician_id: 108,
},
{
	statements: "Suing President Obama for delay of individual mandage",
	body: "Statement on lawsuit against President Obama for delaying individual mandate",
	path: "http://www.speaker.gov/press-release/boehner-about-protecting-constitution",
	politician_id: 108,
},
]
